wildfly-extras/batavia

convert2ee9/pom.xml, convert2ee9/src/main/java/org/convert2ee9/Transformer.java
@ropalka initial check in of convert2ee9 transformer
=> initial add of https://github.com/scottmarlow/convert2ee9

api/src/main/java/org/wildfly/transformer/TransformerFactory.java, impl/asm-based-transformer/src/main/java/org/wildfly/transformer/asm/TransformerFactoryImpl.java, impl/asm-based-transformer/src/main/java/org/wildfly/transformer/asm/TransformerImpl.java, impl/asm-based-transformer/src/main/resources/META-INF/services/org.wildfly.transformer.TransformerFactory, impl/no-deps-transformer/src/main/java/org/wildfly/transformer/nodeps/ClassFileUtils.java, impl/no-deps-transformer/src/main/java/org/wildfly/transformer/nodeps/Main.java, impl/no-deps-transformer/src/main/java/org/wildfly/transformer/nodeps/Transformer.java, impl/no-deps-transformer/src/main/java/org/wildfly/transformer/nodeps/TransformerFactoryImpl.java, impl/no-deps-transformer/src/main/java/org/wildfly/transformer/nodeps/TransformerImpl.java, impl/no-deps-transformer/src/main/resources/META-INF/services/org.wildfly.transformer.TransformerFactory
In order to be able to introduce unified tools code base we
need transformers to implement service loader mechanism.
=> Service loader mechanism

api/src/main/java/org/wildfly/transformer/Transformer.java, impl/asm-based-transformer/src/main/java/org/wildfly/transformer/asm/TransformerImpl.java, impl/no-deps-transformer/src/main/java/org/wildfly/transformer/nodeps/TransformerImpl.java, pom.xml, tools/cmdline/pom.xml, tools/cmdline/src/main/java/org/wildfly/transformer/tool/cmdline/Main.java, tools/pom.xml
This proposal PR introduces new Transformer.Resource inner class.
Migrates both ASM based and no dependencies transformer to leverage this new abstraction.
Finally eliminates all duplicite code in both transformer implementations.
Since now it will be possible to use Main command line tool regardless of transformer implementation.
=> Command line tool now able to use any transformer implementation

tools/src/main/java/org/wildfly/transformer/tool/cmdline/Main.java, tools/src/main/java/org/wildfly/transformer/tool/maven/HandleTransformation.java, tools/src/main/java/org/wildfly/transformer/tool/maven/MavenPluginTransformer.java
- adding license where missing
- fixing whitespaces 
- decreasing some classes and methods visibility
=> Minor code cleanup

impl/no-deps-transformer/src/main/java/org/wildfly/transformer/nodeps/TransformerImpl.java
https://github.com/wildfly-extras/batavia/issues/30
=> [ISSUE-30] Fixing "no dependencies" transformer bug 

api/src/main/java/org/wildfly/transformer/Transformer.java
Fixes https://github.com/wildfly-extras/batavia/issues/39
=> [ISSUE-39] We will not support runtime (on the fly) transformation of classes

api/src/main/java/org/wildfly/transformer/Transformer.java, impl/asm/src/main/java/org/wildfly/transformer/asm/TransformerImpl.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/TransformerImpl.java, tools/api/src/main/java/org/wildfly/transformer/tool/api/ToolUtils.java, tools/cli/src/main/java/org/wildfly/transformer/tool/cli/Main.java, tools/mvn/src/main/java/org/wildfly/transformer/tool/maven/HandleTransformation.java, tools/mvn/src/main/java/org/wildfly/transformer/tool/maven/MavenPluginTransformer.java
Addresses: https://github.com/wildfly-extras/batavia/issues/38
=> [ISSUE-38] Revisiting Transformer API to support adding of additional resources

impl/asm/src/main/java/org/wildfly/transformer/asm/TransformerImpl.java
Updates for ASM based Class.forName handling
=> more Class.forName handling for issues/21

impl/asm/src/main/java/org/wildfly/transformer/asm/TransformerImpl.java
Addresses https://github.com/wildfly-extras/batavia/issues/49
=> [ISSUE-49] bouncycastle transformation requires ASM7 support, so default to that for NestHost attributes

api/src/main/resources/default.mapping, api/src/main/resources/jboss-modules-default.mapping
https://github.com/wildfly-extras/batavia/issues/52
=> [ISSUE-52] Add rule for converting javax.xml.bind=jakarta.xml.bind

impl/asm/src/main/java/org/wildfly/transformer/asm/TransformerImpl.java
Moved handling of checking for modifications into replaceJavaXwithJakarta(), to avoid much repeated code.
Also handled a few more general cases.
=> Handling more cases and some cleanup

impl/asm/src/main/java/org/wildfly/transformer/asm/TransformerImpl.java
Signed-off-by: Scott Marlow <smarlow@redhat.com>
https://github.com/wildfly-extras/batavia/issues/57
=> [issues/57] ASM transformer needs to handle visitFrame

impl/asm/src/main/java/org/wildfly/transformer/asm/TransformerImpl.java
Addresses https://github.com/wildfly-extras/batavia/issues/59
=> [issues/59] Need to handle transforming javax => jakarta for visitTryCatchBlock

impl/nod/src/main/java/org/wildfly/transformer/nodeps/AddMappingPatch.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/ClassFileRefs.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/ClassFileUtils.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/CodeAttributeRefs.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/ConstantPoolRefs.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/ConstantPoolTags.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/JavaLangTransformUtils.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/MethodDescriptor.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/MethodInfoRefs.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/MethodRedirection.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/MethodsPatch.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/MethodsRedirectPatch.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/OpcodeUtils.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/Opcodes.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/TransformerImpl.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/Utf8InfoMapping.java, impl/nod/src/main/java/org/wildfly/transformer/nodeps/Utf8ItemsPatch.java
Processing essential calls with potentially dynamically constructed strings.
With this fix the following calls are intercepted and forwared to generated package private 'utility classes':
* Class.forName()
* ClassLoader.getResource*()
* ClassLoader.loadClass()
* ClassLoader.getSystemResource*()
=> [ISSUE-21] Implemented support for reflection in 'No Dependencies Transformer' 

impl/ecl/src/main/java/org/wildfly/extras/transformer/eclipse/ArchiveTransformerImpl.java
https://github.com/wildfly-extras/batavia/issues/68
=> [ISSUE-68] Support jakarta-direct.properties in eclipse transformer integration code

impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-direct.properties
https://github.com/wildfly-extras/batavia/issues/69
=> [ISSUE-69] Fixing jasper library transformation issues

api/src/main/java/org/wildfly/extras/transformer/Config.java, impl/ecl/src/main/java/org/wildfly/extras/transformer/eclipse/ArchiveTransformerImpl.java, tools/cli/src/main/java/org/wildfly/extras/transformer/tool/cli/Main.java
Fixes https://github.com/wildfly-extras/batavia/issues/72
=> [ISSUE-72] Added support for reading config files from file system

api/src/main/java/org/wildfly/extras/transformer/ArchiveTransformer.java, impl/nod/src/main/java/org/wildfly/extras/transformer/nodeps/MethodsPatch.java, impl/nod/src/main/java/org/wildfly/extras/transformer/nodeps/MethodsRedirectPatch.java, impl/nod/src/main/java/org/wildfly/extras/transformer/nodeps/OpcodeUtils.java, impl/nod/src/main/java/org/wildfly/extras/transformer/nodeps/ResourceTransformerImpl.java, tools/cli/src/main/java/org/wildfly/extras/transformer/tool/cli/Main.java
Fixes https://github.com/wildfly-extras/batavia/issues/64 https://github.com/wildfly-extras/batavia/issues/75 https://github.com/wildfly-extras/batavia/issues/76 https://github.com/wildfly-extras/batavia/issues/77 https://github.com/wildfly-extras/batavia/issues/78
=> 1 usability enhancement and a couple of no dependencies transformer fixes

impl/asm/src/main/java/org/wildfly/extras/transformer/asm/ResourceTransformerImpl.java, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-txt-master.properties, impl/nod/src/main/java/org/wildfly/extras/transformer/nodeps/ResourceTransformerImpl.java
Fixes https://github.com/wildfly-extras/batavia/issues/80
=> [ISSUE-80] Transform also JSP & TLD files

impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/ejb-logger.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/hibernate-core-message-logger.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-per-class.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jxc-ap-annotation-parser.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/logger-messages.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/resteasy-jaxrs-messages.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/ws-common-messages.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/xml-ws-respect-binding.properties
Some more strings to transform.
=> Add some mapping for logger messages

impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-direct.properties
Fixes https://github.com/wildfly-extras/batavia/issues/86
=> [ISSUE-86] Transform also javax.servlet.request.* attributes

impl/ecl/src/main/java/org/wildfly/extras/transformer/eclipse/ArchiveTransformerImpl.java
Signed-off-by: Scott Marlow <smarlow@redhat.com>
=> Fixed minor typo in error message

impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-direct.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-txt-master.properties
Fixes https://github.com/wildfly-extras/batavia/issues/97
=> [ISSUE-97] Handle JAXBContext lookup and jaxb.properties accordingly

api/src/main/java/org/wildfly/extras/transformer/ArchiveTransformer.java, impl/ecl/src/main/java/org/wildfly/extras/transformer/eclipse/ArchiveTransformerImpl.java, tools/mvn/src/main/java/org/wildfly/extras/transformer/tool/maven/HandleTransformation.java, tools/mvn/src/main/java/org/wildfly/extras/transformer/tool/maven/MavenPluginTransformer.java
Allowing the Maven plugin to use a folder with classes and to ouput the transformed classes toa folder so they can be used to produce a new artefact
=> Updating the maven plugin for a better usability

impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-direct.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-txt-master.properties, impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/xml-schema.properties
Signed-off-by: Brian Stansberry <brian.stansberry@redhat.com>
Resolves #101
=> [ISSUE-101] Transform the jaxb xml namespace

impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-direct.properties
https://github.com/wildfly-extras/batavia/issues/104
=> [ISSUE-104] adding javax.faces.resource mapping

tools/mvn/src/main/java/org/wildfly/extras/transformer/tool/maven/SourceTransformerMojo.java
resulting transformed sources and resources to the project if the correct lifecycle phases are used.
=> Adding support to transform sources and resources and attaching the

tools/mvn/src/main/java/org/wildfly/extras/transformer/tool/maven/SourceTransformerMojo.java
Simplifying the execution of source transformation so that it can transform a maven project with the standard layout
=> Supporting maven project with default layout

api/src/main/java/org/wildfly/extras/transformer/ArchiveTransformer.java, api/src/main/java/org/wildfly/extras/transformer/ResourceTransformer.java, api/src/main/java/org/wildfly/extras/transformer/TransformerBuilder.java, impl/asm/src/main/java/org/wildfly/extras/transformer/asm/ArchiveTransformerImpl.java, impl/asm/src/main/java/org/wildfly/extras/transformer/asm/ResourceTransformerImpl.java, impl/asm/src/main/java/org/wildfly/extras/transformer/asm/TransformerBuilderImpl.java, impl/ecl/src/main/java/org/wildfly/extras/transformer/eclipse/ArchiveTransformerImpl.java, impl/ecl/src/main/java/org/wildfly/extras/transformer/eclipse/TransformerBuilderImpl.java, impl/nod/src/main/java/org/wildfly/extras/transformer/nodeps/ArchiveTransformerImpl.java, impl/nod/src/main/java/org/wildfly/extras/transformer/nodeps/ResourceTransformerImpl.java, impl/nod/src/main/java/org/wildfly/extras/transformer/nodeps/TransformerBuilderImpl.java, tools/mvn/src/main/java/org/wildfly/extras/transformer/tool/maven/HandleTransformation.java, tools/mvn/src/main/java/org/wildfly/extras/transformer/tool/maven/MavenPluginTransformer.java, tools/mvn/src/main/java/org/wildfly/extras/transformer/tool/maven/SourceTransformerMojo.java
Allowing to invert the trasformation
=> Adding support to invert transformation

tools/mvn/src/main/java/org/wildfly/extras/transformer/tool/maven/HandleTransformation.java, tools/mvn/src/main/java/org/wildfly/extras/transformer/tool/maven/SourceTransformerMojo.java
=> Ignore transforming files that are already in the source directory.
